install.packages(c("tidyverse",
    "here",
    "UpSetR",
    "gridExtra",
    "roxygen2",
    "docstring",
    "igraph",
    "ape",
    "phylogram",
    "phytools",
    "msa",
    "seqinr",
    "ggtree",
    "tidytree",
    "Rcpp",
    "tidytext"), dependencies=T)
